# .github/workflows/deploy.yml

name: Deploy Laravel via SSH

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Jalankan deploy lewat SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/KKN-TEMATIK-ASIK
            echo "Pulling from repo"
            git pull origin dev
            echo "Git status"
            git status
            php artisan migrate --force
            php artisan db:seed --force
            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear
            php artisan route:clear
